openapi: 3.0.0
info:
  title: Supabase Proxy API
  version: 1.0.0

paths:
  /{proxy+}:
    get:
      operationId: proxyGet
      parameters:
        - name: proxy
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e8tkatoo41i2417l4m
        tag: $latest
      responses:
        '200':
          description: OK
    post:
      operationId: proxyPost
      parameters:
        - name: proxy
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e8tkatoo41i2417l4m
        tag: $latest
      responses:
        '200':
          description: OK
    put:
      operationId: proxyPut
      parameters:
        - name: proxy
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e8tkatoo41i2417l4m
        tag: $latest
      responses:
        '200':
          description: OK
    patch:
      operationId: proxyPatch
      parameters:
        - name: proxy
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e8tkatoo41i2417l4m
        tag: $latest
      responses:
        '200':
          description: OK
    delete:
      operationId: proxyDelete
      parameters:
        - name: proxy
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e8tkatoo41i2417l4m
        tag: $latest
      responses:
        '200':
          description: OK
    options:
      operationId: corsProxy
      parameters:
        - name: proxy
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e8tkatoo41i2417l4m
        tag: $latest
      responses:
        '200':
          description: CORS OK

x-yc-apigateway-cors:
  enabled: true
  allow-headers:
    - authorization
    - x-client-info
    - apikey
    - content-type
    - x-requested-with
    - accept
    - origin
    - prefer
    - range
    - x-supabase-api-version
    - content-profile
    - accept-profile
  allow-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allow-origins:
    - 'https://stwarehouse.website.yandexcloud.net'
    - 'https://stwarehouse.vercel.app'
    - 'http://localhost:5173'
    - 'http://localhost:3000'
